# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Chirpy to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' depending on your branch name

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
